default_language_version:
  python: python3
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files", "src", "tests" ]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [ "--safe", "src", "tests" ]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
        args: [ "--max-line-length=100", "--extend-ignore=E203", "src", "tests", ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        pass_filenames: false
        args: [ "--no-strict-optional", "--ignore-missing-imports", "src" ]
