name: Tests

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      - ".pre-commit-config.yaml"
      - "requirements-dev.txt"
      - "version.txt"
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      - ".pre-commit-config.yaml"
      - "requirements-dev.txt"
      - "version.txt"
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10 - 3.11']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Python ${{ steps.cp310.outputs.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
